spring:
  application:
    name: planner-users

  datasource:
    url: jdbc:postgresql://localhost:5432/planner_users
    username: root
    password: root


eureka:
  client:
    service-url:
      defautl-zone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"



