spring:
  application:
    name: planner-todo

  datasource:
    url: jdbc:postgresql://localhost:5432/planner_tasks
    username: root
    password: root


eureka:
  client:
    service-url:
      defautl-zone: http://localhost:8761/eureka


check: some string