server:
  port: 8765

spring:
  application:
    name: planner-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
     
    

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
 
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        
check: some string